### ISSUE TITLE
Enable naming lint

### ISSUE THREAD

**Issue by dalance** [veryl-lang/std#7]
The current modules follow almost same naming rule.
So the explicit naming lint configuration can be applied.

```toml
[lint.naming]
case_enum          = "snake"
case_function      = "snake"
case_instance      = "snake"
case_interface     = "snake"
case_modport       = "snake"
case_module        = "snake"
case_package       = "snake"
case_parameter     = "screaming_snake"
case_port_inout    = "snake"
case_port_input    = "snake"
case_port_modport  = "snake"
case_port_output   = "snake"
case_reg           = "snake"
case_struct        = "snake"
case_union         = "snake"
case_var           = "snake"
case_wire          = "snake"
prefix_port_input  = "i_"
prefix_port_output = "o_"
```
